services:
  mongoIB:
    image: mongo:7.0
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27018", "--bind_ip", "localhost"]
    container_name: "mongoIB"
    ports:
      - 27018:27018
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"
    networks:
      - mongoIBCluster

volumes:
  mongo_data:
  mongo_config: