services:
  mongo2:
    image: mongo:7.0
    command: ["--name", "mongo2", "--replSet", "rs0", "--bind_ip_all", "--port", "27018", "--network", "networkTest", "--bind_ip", "localhost"]
    ports:
      - 27018:27018
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"

volumes:
  mongo1_data:
  mongo1_config: