services:
  mongoib:
    container_name: "mongoIB"
    ports:
      - "0.0.0.0:443:27017"
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoIB
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoIB
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    build: ./mongoDB


volumes:
  mongo_data:
  mongo_config: