version: '7.0'
services:
  mongoib:
    container_name: "mongoIB"
    ports:
      - 27019:27019
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"
    networks:
      - mongoIBCluster
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoIB
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27019
    build: ./mongoDB


volumes:
  mongo_data:
  mongo_config:

networks:
  mongoIBCluster:
    driver: bridge